name: HIFITI-Auto-Checkin

on:
  workflow_dispatch:
  schedule:
    # UTC
    - cron: "40 23 * * *"

jobs:
  checkin:
    name: Checkin
    runs-on: ubuntu-latest
    env:
      ACCOUNTS: ${{ secrets.ACCOUNTS }}
      TELEGRAM_TOKEN: ${{ secrets.TELEGRAM_TOKEN }}
      TELEGRAM_TO: ${{ secrets.TELEGRAM_TO }}

    steps:
      - uses: actions/checkout@v6

      - name: Use Node.js latest.
        uses: actions/setup-node@v6
        with:
          node-version: latest

      - name: Checkin
        id: checkin
        shell: bash
        run: |
          node main.js

      - name: Notify
        if: ${{ always() && env.TELEGRAM_TOKEN && env.TELEGRAM_TO }}
        uses: appleboy/telegram-action@master
        with:
          to: ${{ secrets.TELEGRAM_TO }}
          token: ${{ secrets.TELEGRAM_TOKEN }}
          format: markdown
          message: |
            *HIFINI 自动签到*

            ${{ steps.checkin.outputs.result  }}

            [任务详情](https://github.com/${{ github.repository }}/actions/runs/${{ github.run_id }})
